version: '2.1'
services:
  myapp:
    image: 'bitnami/codeigniter:latest'
    container_name: application_peternakan
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:8000'
    volumes:
      - '.:/app'
    depends_on:
      - mariadb
  mariadb: 
    image : mysql:8.0.2
    container_name: database_peternakan
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: peternakan_app
    ports:
      - "3306:3306"
    volumes:
      - "./my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./data_mysql:/var/lib/mysql:rw"
  # mariadb:
  #   image: 'bitnami/mysql:latest'
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   volumes:
  #     - ./data:/bitnami/mysql/data
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - mariadb
    ports:
      - '8080:80'
      - '443:443'
    # volumes:
    #   - ./path/to/phpmyadmin-persistence:/bitnami
